### ISSUE TITLE
Prometheus pump config port not working

### ISSUE THREAD

**Issue by MyMirelHub** [TykTechnologies/tyk-pump#132]
**What did I do?**

1. I added the prometheus config for the tyk-pump as given in the docs: 

```
"prometheus": {
    "type": "prometheus",
    "meta": {
      "listen_address": "localhost:9090",
      "path": "/metrics"
    }
  },
```

2. Applied the new `pump.conf` file and restarted my tyk pods. 

3. Set up a service to expose the metrics port

```yaml
apiVersion: "v1"
kind: "Service"
metadata:
  name: "tyk-pump-service"
  namespace: "tyk"
  labels:
    app: "tyk-pump"
spec:
  ports:
  - name: metrics
    protocol: "TCP"
    port: 9090
    targetPort: 9090
  selector:
    app: "tyk-pump"
  type: "ClusterIP"
```
**Problem Encountered**

When trying to port-forward the service to display the prometheus metrics
```sh
kubectl port-forward svc/tyk-pump-service 9090
```

I get: 

```
E0806 17:08:42.586483   43832 portforward.go:400] an error occurred forwarding 9090 -> 9090: error forwarding port 9090 to pod e1206bd8d15c815021d8a17dcd61fdd887624ab591bb6f0f609c26f91f17b326, uid : exit status 1: 2019/08/06 16:08:42 socat[2382373] E connect(5, AF=2 127.0.0.1:9090, 16): Connection refused
```

Then I tried connected to the pod: 

```
kubectl exec -it tyk-pump-pod -- /bin/sh
```

and run `netstat -l`, I get no listening ports. 

```
etstat -l
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
Active UNIX domain sockets (only servers)
```
